# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba42ab1a9f6f9cf22462c5f279e0eec7030da93b91772701a1b360408eb0bfb57f9f88e07c28ce984d340e55b79f3d1cd4987d508a5aa81ffcfab7907bbdce9a

test:
  secret_key_base: 81bf17dceafe0dc5a21eb6fd0eb4c6c253b01beb06151109f266e45bfb841094fd32628272b976860d1b21a862d2c5b99313172dee349e99b23c7e33672d9a84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
